n = input('Digite qualquer valor: ')
print('O tipo primitivo é ', type(n))
print(n.isalpha())
print(n.isnumeric())
print(n.isdecimal())
print(n.isupper())
print(n.islower())
print(n.isascii())
print(n.istitle())